/*
 * gen_grid.cc — Generate square grid graphs in DIMACS format
 *
 * Creates a W×W grid where each node connects to its 4 neighbors
 * (up, down, left, right) with random integer weights in [1, maxW].
 *
 * Output: DIMACS .gr file (graph) and .ss file (random sources)
 *
 * Grid topology is important for SSSP benchmarks because:
 *   - Unlike road networks, grids have uniform degree (4)
 *   - No hierarchy or natural clustering
 *   - Tests whether bucket queue advantages persist beyond road networks
 *
 * Build:
 *   g++ -std=c++17 -Wall -O3 -o gen_grid gen_grid.cc
 *
 * Usage:
 *   ./gen_grid <width> <maxWeight> <seed> <out_prefix>
 *   Example: ./gen_grid 1000 1000 42 grid1000
 *     → grid1000.gr (1M nodes, ~4M arcs)
 *     → grid1000.ss (100 random sources)
 */

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>

int main(int argc, char **argv)
{
    if (argc != 5) {
        fprintf(stderr, "Usage: %s <width> <maxWeight> <seed> <out_prefix>\n", argv[0]);
        fprintf(stderr, "Example: %s 1000 1000 42 grid1000\n", argv[0]);
        return 1;
    }

    int W = atoi(argv[1]);
    int maxW = atoi(argv[2]);
    unsigned seed = (unsigned)atoi(argv[3]);
    const char *prefix = argv[4];

    long long N = (long long)W * W;
    /* Each interior node has 4 edges, border nodes have 2-3.
     * Total arcs = 2 * (2*W*(W-1)) = 4*W*(W-1) for a grid.
     * But DIMACS uses directed arcs, so each undirected edge → 2 arcs. */
    long long M = 2LL * (2LL * W * ((long long)W - 1));

    fprintf(stderr, "Generating %dx%d grid: %lld nodes, %lld arcs, maxWeight=%d, seed=%u\n",
            W, W, N, M, maxW, seed);

    if (N > 100000000LL) {
        fprintf(stderr, "ERROR: grid too large (>100M nodes)\n");
        return 1;
    }

    /* ---- Generate .gr file ---- */
    char grName[512], ssName[512];
    snprintf(grName, sizeof(grName), "%s.gr", prefix);
    snprintf(ssName, sizeof(ssName), "%s.ss", prefix);

    FILE *gr = fopen(grName, "w");
    if (!gr) { fprintf(stderr, "ERROR: cannot open %s\n", grName); return 1; }

    fprintf(gr, "c Grid graph %dx%d, maxWeight=%d, seed=%u\n", W, W, maxW, seed);
    fprintf(gr, "c Generated by gen_grid.cc for OMBI paper experiments\n");
    fprintf(gr, "p sp %lld %lld\n", N, M);

    std::mt19937 rng(seed);
    std::uniform_int_distribution<int> wdist(1, maxW);

    /* Node numbering: node(r,c) = r*W + c + 1 (1-indexed for DIMACS) */
    /* Edges: right, down (and their reverses) */

    long long arcCount = 0;
    for (int r = 0; r < W; r++) {
        for (int c = 0; c < W; c++) {
            int u = r * W + c + 1;  /* 1-indexed */

            /* Right neighbor */
            if (c + 1 < W) {
                int v = r * W + (c + 1) + 1;
                int w1 = wdist(rng);
                int w2 = wdist(rng);
                fprintf(gr, "a %d %d %d\n", u, v, w1);
                fprintf(gr, "a %d %d %d\n", v, u, w2);
                arcCount += 2;
            }

            /* Down neighbor */
            if (r + 1 < W) {
                int v = (r + 1) * W + c + 1;
                int w1 = wdist(rng);
                int w2 = wdist(rng);
                fprintf(gr, "a %d %d %d\n", u, v, w1);
                fprintf(gr, "a %d %d %d\n", v, u, w2);
                arcCount += 2;
            }
        }
    }

    fclose(gr);
    fprintf(stderr, "Wrote %s: %lld arcs (expected %lld)\n", grName, arcCount, M);

    /* ---- Generate .ss file (100 random sources) ---- */
    FILE *ss = fopen(ssName, "w");
    if (!ss) { fprintf(stderr, "ERROR: cannot open %s\n", ssName); return 1; }

    fprintf(ss, "c Random sources for grid %dx%d\n", W, W);
    fprintf(ss, "p aux sp ss %lld\n", (long long)100);

    std::uniform_int_distribution<int> sdist(1, (int)N);
    for (int i = 0; i < 100; i++) {
        fprintf(ss, "s %d\n", sdist(rng));
    }

    fclose(ss);
    fprintf(stderr, "Wrote %s: 100 random sources\n", ssName);

    return 0;
}
